### ISSUE TITLE
README

### ISSUE THREAD

**Issue by Stannlag** [RetroMizik/Streamer#2]
Update the Readme file. Create two categories:
Basic Functionality and Optionnal functionality.
@sonfresh
@RetroMizik/alafia

**Comment by Sonfresh** [comment]
It's done!

**Comment by Stannlag** [comment]
I think we must remove some of the basic functionnality. Like the one where the user can download misic,

**Comment by Sonfresh** [comment]
It's done!

**Comment by Sonfresh** [comment]
It's done! 
@Stannlag

**Comment by Stannlag** [comment]
Good!
